//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo2
    {
        public int IDEvento { get; set; }
        public string Evento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
